<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TransferSeeder extends Seeder
{
    public function run()
    {
        DB::table('transfers')->insert([
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 2,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 2,
                'to_warehouse_id' => 3,
                'product_id' => 3,
                'quantity' => 50,
                'transfer_date' => Carbon::now()->subDays(2)->format('Y-m-d'),
                'status' => 'accepted',
                'is_received' => true,
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'from_warehouse_id' => 3,
                'to_warehouse_id' => 1,
                'product_id' => 3,
                'quantity' => 200,
                'transfer_date' => Carbon::now()->subDays(5)->format('Y-m-d'),
                'status' => 'rejected',
                'is_received' => false,
                'created_at' => Carbon::now()->subDays(5),
                'updated_at' => Carbon::now()->subDays(4),
            ],
            
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 3,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 4,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 5,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 6,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 7,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 8,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 9,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 10,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 11,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 12,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 13,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 14,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 15,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 16,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 17,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 18,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 19,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'from_warehouse_id' => 1,
                'to_warehouse_id' => 20,
                'product_id' => 1,
                'quantity' => 100,
                'transfer_date' => Carbon::now()->format('Y-m-d'),
                'status' => 'pending',
                'is_received' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
        ]);
    }
}

